"""Initial_schema_migration

Revision ID: 3007fc95a023
Revises: 
Create Date: 2026-06-23 12:54:04.570033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3007fc95a023'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('facility_id', sa.String(length=50), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('terminal', sa.String(length=10), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('x_coordinate', sa.Float(), nullable=False),
    sa.Column('y_coordinate', sa.Float(), nullable=False),
    sa.Column('operating_hours', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('facility_id')
    )
    op.create_index(op.f('ix_facilities_category'), 'facilities', ['category'], unique=False)
    op.create_index(op.f('ix_facilities_facility_id'), 'facilities', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facilities_terminal'), 'facilities', ['terminal'], unique=False)
    op.create_table('flights',
    sa.Column('flight_id', sa.String(length=50), nullable=False),
    sa.Column('airline', sa.String(length=100), nullable=False),
    sa.Column('flight_number', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('scheduled_departure', sa.DateTime(), nullable=False),
    sa.Column('scheduled_arrival', sa.DateTime(), nullable=False),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('actual_arrival', sa.DateTime(), nullable=True),
    sa.Column('gate_number', sa.String(length=50), nullable=True),
    sa.Column('terminal', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=False),
    sa.Column('delay_minutes', sa.Float(), nullable=True),
    sa.Column('delay_reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('flight_id')
    )
    op.create_index(op.f('ix_flights_flight_id'), 'flights', ['flight_id'], unique=False)
    op.create_index(op.f('ix_flights_scheduled_departure'), 'flights', ['scheduled_departure'], unique=False)
    op.create_index(op.f('ix_flights_terminal'), 'flights', ['terminal'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_model_name'), 'model_metrics', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_metrics_trained_at'), 'model_metrics', ['trained_at'], unique=False)
    op.create_table('parking',
    sa.Column('parking_id', sa.String(length=50), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('occupied_slots', sa.Integer(), nullable=False),
    sa.Column('occupancy_ratio', sa.Float(), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('distance_to_terminal_m', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('parking_id')
    )
    op.create_index(op.f('ix_parking_timestamp'), 'parking', ['timestamp'], unique=False)
    op.create_index(op.f('ix_parking_zone_name'), 'parking', ['zone_name'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('predicted_wait_time', sa.Float(), nullable=True),
    sa.Column('predicted_congestion', sa.String(length=50), nullable=True),
    sa.Column('predicted_delay', sa.Float(), nullable=True),
    sa.Column('predicted_facility_utilization', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_timestamp'), 'predictions', ['timestamp'], unique=False)
    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('checkpoint', sa.String(length=100), nullable=False),
    sa.Column('queue_length', sa.Integer(), nullable=False),
    sa.Column('wait_time', sa.Float(), nullable=False),
    sa.Column('congestion_level', sa.String(length=50), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_results_checkpoint'), 'simulation_results', ['checkpoint'], unique=False)
    op.create_index(op.f('ix_simulation_results_scenario_name'), 'simulation_results', ['scenario_name'], unique=False)
    op.create_index(op.f('ix_simulation_results_timestamp'), 'simulation_results', ['timestamp'], unique=False)
    op.create_table('weather',
    sa.Column('weather_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=False),
    sa.Column('wind_speed_kmph', sa.Float(), nullable=False),
    sa.Column('visibility_km', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=False),
    sa.Column('forecast_horizon_hrs', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_index(op.f('ix_weather_timestamp'), 'weather', ['timestamp'], unique=False)
    op.create_table('directions',
    sa.Column('direction_id', sa.String(length=50), nullable=False),
    sa.Column('from_location_id', sa.String(length=50), nullable=False),
    sa.Column('from_location_name', sa.String(length=200), nullable=False),
    sa.Column('to_location_id', sa.String(length=50), nullable=False),
    sa.Column('to_location_name', sa.String(length=200), nullable=False),
    sa.Column('path_description', sa.Text(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('estimated_walk_time_min', sa.Float(), nullable=False),
    sa.Column('terminal', sa.String(length=50), nullable=False),
    sa.Column('floor_change_flag', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['facilities.facility_id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('direction_id')
    )
    op.create_index(op.f('ix_directions_from_location_id'), 'directions', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_directions_to_location_id'), 'directions', ['to_location_id'], unique=False)
    op.create_table('facility_occupancy',
    sa.Column('occupancy_id', sa.String(length=50), nullable=False),
    sa.Column('facility_id', sa.String(length=50), nullable=False),
    sa.Column('facility_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('terminal', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('occupancy_count', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupancy_ratio', sa.Float(), nullable=False),
    sa.Column('crowd_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.facility_id'], ),
    sa.PrimaryKeyConstraint('occupancy_id')
    )
    op.create_index(op.f('ix_facility_occupancy_facility_id'), 'facility_occupancy', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_occupancy_terminal'), 'facility_occupancy', ['terminal'], unique=False)
    op.create_index(op.f('ix_facility_occupancy_timestamp'), 'facility_occupancy', ['timestamp'], unique=False)
    op.create_table('passengers',
    sa.Column('passenger_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('pnr_booking_ref', sa.String(length=50), nullable=False),
    sa.Column('flight_id', sa.String(length=50), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=False),
    sa.Column('ticket_class', sa.String(length=50), nullable=False),
    sa.Column('checkin_status', sa.String(length=50), nullable=False),
    sa.Column('special_assistance_flag', sa.Boolean(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.flight_id'], ),
    sa.PrimaryKeyConstraint('passenger_id')
    )
    op.create_index(op.f('ix_passengers_flight_id'), 'passengers', ['flight_id'], unique=False)
    op.create_index(op.f('ix_passengers_passenger_id'), 'passengers', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_passengers_pnr_booking_ref'), 'passengers', ['pnr_booking_ref'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('passenger_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.passenger_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_passenger_id'), 'users', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('detected_intent', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_logs_session_id'), 'chat_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_timestamp'), 'chat_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_logs_user_id'), 'chat_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_logs_user_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_timestamp'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_session_id'), table_name='chat_logs')
    op.drop_table('chat_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_passenger_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_passengers_pnr_booking_ref'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_passenger_id'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_flight_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_facility_occupancy_timestamp'), table_name='facility_occupancy')
    op.drop_index(op.f('ix_facility_occupancy_terminal'), table_name='facility_occupancy')
    op.drop_index(op.f('ix_facility_occupancy_facility_id'), table_name='facility_occupancy')
    op.drop_table('facility_occupancy')
    op.drop_index(op.f('ix_directions_to_location_id'), table_name='directions')
    op.drop_index(op.f('ix_directions_from_location_id'), table_name='directions')
    op.drop_table('directions')
    op.drop_index(op.f('ix_weather_timestamp'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_simulation_results_timestamp'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_scenario_name'), table_name='simulation_results')
    op.drop_index(op.f('ix_simulation_results_checkpoint'), table_name='simulation_results')
    op.drop_table('simulation_results')
    op.drop_index(op.f('ix_predictions_timestamp'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_parking_zone_name'), table_name='parking')
    op.drop_index(op.f('ix_parking_timestamp'), table_name='parking')
    op.drop_table('parking')
    op.drop_index(op.f('ix_model_metrics_trained_at'), table_name='model_metrics')
    op.drop_index(op.f('ix_model_metrics_model_name'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_flights_terminal'), table_name='flights')
    op.drop_index(op.f('ix_flights_scheduled_departure'), table_name='flights')
    op.drop_index(op.f('ix_flights_flight_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_facilities_terminal'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_category'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
